version: "3.9"
volumes:
  psysh-store:
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
      target: production
    volumes:
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    container_name: backend-container
    hostname: backend-server
    ports:
      - "9000:9000"
    environment:
      - APP_DEBUG=false
      - APP_ENV=production
      - APP_URL=${APP_URL:-api.aws-and-infra-ts.click}
      - LOG_CHANNEL=stderr
      - LOG_STDERR_FORMATTER=Monolog\Formatter\JsonFormatter
      - DB_CONNECTION=${DB_CONNECTION:-mysql}
      - DB_HOST=${DB_HOST:-fullcalendar-db.c8hocvhhmv4b.ap-northeast-1.rds.amazonaws.com}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-fullcalendar}
      - DB_USERNAME=${DB_USERNAME:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-passowrd}

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
      target: production
    container_name: web-container
    hostname: web-server
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    depends_on:
      - backend

  mailhog:
    image: mailhog/mailhog
    container_name: mail-container
    hostname: mail-server
    ports:
      - target: 8025
        published: 8025
        protocol: tcp
        mode: host